#!/bin/sh
[ -d "$XMLSH" ] || { echo "xmlsh requires environment variable XMLSH set" 1>&2 ;  exit 1 ; }
# cygwin uses ";" separator because java is still a win app.
export CP="$XMLSH/bin/*;$XMLSH/lib/*"
[ -z "$XMLSH_JVMOPTS" ] &&  export XMLSH_JVMOPTS="-XX:+UseConcMarkSweepGC -Xmx1024m -Xms256m"
java -cp "$CP" $XMLSH_JVMOPTS org.xmlsh.sh.shell.Shell   "$@"
