/* Generated By:JavaCC: Do not edit this line. ShellParserConstants.java */
package org.xmlsh.sh.grammar;
 
public interface ShellParserConstants {

  int EOF = 0;
  int NEWLINE = 4;
  int SINGLE_LINE_COMMENT = 5;
  int CSEMI = 6;
  int AND_IF = 7;
  int OR_IF = 8;
  int DSEMI = 9;
  int DLESS = 10;
  int DGREAT = 11;
  int LESSAND = 12;
  int GREATAND = 13;
  int LESSGREAT = 14;
  int DLESSDASH = 15;
  int CLOBBER = 16;
  int IF = 17;
  int ELIF = 18;
  int THEN = 19;
  int ELSE = 20;
  int FI = 21;
  int DO = 22;
  int DONE = 23;
  int CASE = 24;
  int ESAC = 25;
  int WHILE = 26;
  int UNTIL = 27;
  int FOR = 28;
  int LBRACE = 29;
  int BANG = 30;
  int LPAREN = 31;
  int RBRACE = 32;
  int IN = 33;
  int LESS = 34;
  int GT = 35;
  int TGT = 36;
  int RPAREN = 37;
  int AMP = 38;
  int SEMI = 39;
  int PIPE = 40;
  int NAME = 41;
  int XEXPR = 42;
  int WORD = 43;
  int IO_NUMBER = 44;
  int STRING_LITERAL1 = 45;
  int STRING_LITERAL2 = 46;
  int VAR_EXPANSION = 47;
  int VAR_SUBPROC = 48;
  int ASSIGN_WORD = 49;

  int DEFAULT = 0;
  int CMD = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "\";\"",
    "\"&&\"",
    "\"||\"",
    "\";;\"",
    "\"<<\"",
    "\">>\"",
    "\"<&\"",
    "\">&\"",
    "\"<>\"",
    "\"<<-\"",
    "\">|\"",
    "\"if\"",
    "\"elif\"",
    "\"then\"",
    "\"else\"",
    "\"fi\"",
    "\"do\"",
    "\"done\"",
    "\"case\"",
    "\"esac\"",
    "\"while\"",
    "\"until\"",
    "\"for\"",
    "\"{\"",
    "\"!\"",
    "\"(\"",
    "\"}\"",
    "\"in\"",
    "\"<\"",
    "\">\"",
    "\"2>\"",
    "\")\"",
    "\"&\"",
    "\";\"",
    "\"|\"",
    "<NAME>",
    "\"<[\"",
    "<WORD>",
    "<IO_NUMBER>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<VAR_EXPANSION>",
    "<VAR_SUBPROC>",
    "<ASSIGN_WORD>",
  };

}
