/* Generated By:JavaCC: Do not edit this line. ShellParserTokenManager.java */
package org.xmlsh.sh.grammar;
import org.xmlsh.sh.core.*;
import java.io.PrintWriter;
import java.util.ArrayList;
import org.xmlsh.core.XEnvironment;
 
public class ShellParserTokenManager implements ShellParserConstants
{
  boolean in_for = false ;

  private String readXExpr()
  {
        StringBuffer sb = new StringBuffer("<[");
        char c;
        try {
                while( (c=input_stream.readChar())> 0 ) {
                        sb.append(c);
                        if( sb.toString().endsWith( "]>") )
                                break;
                }
        } catch( Exception e ){}
        return sb.toString();
  }

    String readHere(String here_end)
  {
        StringBuffer sb = new StringBuffer("");
        char c;
        String estr = "\n" + here_end + "\n";
        try {
                while( (c=input_stream.readChar())> 0 ) {
                        if( c == '\r' )
                                continue;
                        sb.append(c);
                        if( c == '\n' &&
                                 sb.toString().endsWith( estr ) ){
                                 sb.setLength( sb.length() - estr.length() + 1 );
                                 input_stream.backup(1);
                                break;
                                 }
                }
        } catch( Exception e ){}
        return sb.toString();
  }

  private String readParen()
  {
        StringBuffer sb = new StringBuffer("");
        char c;
        int endp = 0;
        boolean escaped = false;
        char quoted = '\0';
        try {
                while( (c=input_stream.readChar())> 0 ) {
                        sb.append(c);


                        if( c == '\\' ){
                                escaped=true;
                                continue;
                        }
                        if( ! escaped ){
                                if( quoted == c ){
                                        quoted = '\0';
                                        continue;
                                }

                                if( quoted == '\0' ){
                                        if( c == '"' || c == '\'' )
                                                quoted = c ;

                                        else
                                        if( c == '(' )
                                                endp++;
                                        else
                                        if( c == ')' )
                                        {
                                                if( endp-- <= 0 )
                                                        break;
                                        }
                                }
                        }
                        escaped = false ;
                }
        } catch( Exception e ){}
        return sb.toString();
  }
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x120000000L) != 0L)
            return 36;
         if ((active0 & 0x1ffe0000L) != 0L)
         {
            jjmatchedKind = 41;
            return 36;
         }
         return -1;
      case 1:
         if ((active0 & 0xe20000L) != 0L)
            return 36;
         if ((active0 & 0x1f1c0000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 41;
               jjmatchedPos = 1;
            }
            return 36;
         }
         return -1;
      case 2:
         if ((active0 & 0x10000000L) != 0L)
            return 36;
         if ((active0 & 0xf9c0000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 2;
            return 36;
         }
         return -1;
      case 3:
         if ((active0 & 0x39c0000L) != 0L)
            return 36;
         if ((active0 & 0xc000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 3;
            return 36;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 4);
      case 33:
         return jjStopAtPos(0, 30);
      case 40:
         return jjStopAtPos(0, 31);
      case 41:
         return jjStopAtPos(0, 37);
      case 59:
         return jjStopAtPos(0, 6);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0xc00000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x2140000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x10200000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 123:
         return jjStartNfaWithStates_0(0, 29, 36);
      case 125:
         return jjStartNfaWithStates_0(0, 32, 36);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 91:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 42);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 102:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(1, 17, 36);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x4080000L);
      case 105:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(1, 21, 36);
         break;
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x140000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L);
      case 111:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x10800000L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4040000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 114:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(2, 28, 36);
         break;
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x1100000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 99:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 36);
         break;
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 36);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 36);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 36);
         break;
      case 102:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 36);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 110:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 36);
         break;
      case 108:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 27, 36);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 36;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 36:
                  if ((0x87ffc40000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 61)
                  {
                     if (kind > 49)
                        kind = 49;
                  }
                  else if (curChar == 36)
                     jjCheckNAdd(13);
                  if ((0x87ffc40000000000L & l) != 0L)
                  {
                     if (kind > 41)
                        kind = 41;
                     jjCheckNAddStates(4, 6);
                  }
                  else if (curChar == 36)
                     jjCheckNAdd(12);
                  if (curChar == 36)
                     jjCheckNAdd(6);
                  if (curChar == 36)
                     jjCheckNAdd(5);
                  break;
               case 0:
                  if ((0x87ffc40000000000L & l) != 0L)
                  {
                     if (kind > 41)
                        kind = 41;
                     jjCheckNAddStates(7, 13);
                  }
                  else if (curChar == 39)
                     jjCheckNAddStates(14, 17);
                  else if (curChar == 34)
                     jjCheckNAddStates(18, 23);
                  else if (curChar == 36)
                     jjCheckNAddStates(24, 27);
                  else if (curChar == 35)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(1);
                  }
                  if (curChar == 36)
                     jjCheckNAddTwoStates(5, 12);
                  break;
               case 1:
                  if ((0xfffffffffffffbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if ((0x87ffc40000000000L & l) == 0L)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAddStates(7, 13);
                  break;
               case 3:
                  if ((0x87ffc40000000000L & l) == 0L)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAddStates(4, 6);
                  break;
               case 4:
                  if (curChar == 36)
                     jjCheckNAdd(5);
                  break;
               case 5:
                  if ((0x83ff040800000000L & l) == 0L)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAddStates(28, 31);
                  break;
               case 7:
                  jjAddStates(32, 33);
                  break;
               case 9:
                  if (curChar == 36)
                     jjCheckNAdd(6);
                  break;
               case 10:
                  if ((0x87ffc40000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 11:
                  if (curChar == 36)
                     jjCheckNAdd(12);
                  break;
               case 12:
                  if ((0x83ff040800000000L & l) != 0L)
                     jjCheckNAddStates(34, 38);
                  break;
               case 14:
                  jjAddStates(39, 40);
                  break;
               case 16:
                  if (curChar == 36)
                     jjCheckNAdd(13);
                  break;
               case 17:
                  if (curChar == 61 && kind > 49)
                     kind = 49;
                  break;
               case 18:
                  if (curChar == 36)
                     jjCheckNAddTwoStates(5, 12);
                  break;
               case 19:
                  if (curChar == 36)
                     jjCheckNAddStates(24, 27);
                  break;
               case 20:
                  if (curChar == 40 && kind > 48)
                     kind = 48;
                  break;
               case 21:
                  if (curChar == 60)
                     jjCheckNAdd(20);
                  break;
               case 22:
                  if (curChar == 34)
                     jjCheckNAddStates(18, 23);
                  break;
               case 23:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(41, 43);
                  break;
               case 25:
                  jjCheckNAddStates(41, 43);
                  break;
               case 26:
                  if (curChar == 34 && kind > 41)
                     kind = 41;
                  break;
               case 27:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(44, 46);
                  break;
               case 29:
                  jjCheckNAddStates(44, 46);
                  break;
               case 30:
                  if (curChar == 34)
                     jjCheckNAdd(17);
                  break;
               case 31:
                  if (curChar == 39)
                     jjCheckNAddStates(14, 17);
                  break;
               case 32:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(32, 33);
                  break;
               case 33:
                  if (curChar == 39 && kind > 41)
                     kind = 41;
                  break;
               case 34:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(34, 35);
                  break;
               case 35:
                  if (curChar == 39)
                     jjCheckNAdd(17);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 36:
                  if ((0x2ffffffeaffffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  if ((0x2ffffffeaffffffeL & l) != 0L)
                  {
                     if (kind > 41)
                        kind = 41;
                     jjCheckNAddStates(4, 6);
                  }
                  break;
               case 0:
                  if ((0x2ffffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAddStates(7, 13);
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((0x2ffffffeaffffffeL & l) == 0L)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAddStates(4, 6);
                  break;
               case 5:
                  if ((0x7fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAddStates(28, 31);
                  break;
               case 6:
                  if (curChar == 123)
                     jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 8:
                  if (curChar != 125)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAddStates(4, 6);
                  break;
               case 10:
                  if ((0x2ffffffeaffffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 12:
                  if ((0x7fffffe87ffffffL & l) != 0L)
                     jjCheckNAddStates(34, 38);
                  break;
               case 13:
                  if (curChar == 123)
                     jjCheckNAdd(14);
                  break;
               case 14:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(14, 15);
                  break;
               case 15:
                  if (curChar == 125)
                     jjCheckNAddStates(0, 3);
                  break;
               case 23:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(41, 43);
                  break;
               case 24:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  jjCheckNAddStates(41, 43);
                  break;
               case 27:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(44, 46);
                  break;
               case 28:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  jjCheckNAddStates(44, 46);
                  break;
               case 32:
                  jjAddStates(47, 48);
                  break;
               case 34:
                  jjAddStates(49, 50);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 7:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(32, 33);
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(39, 40);
                  break;
               case 23:
               case 25:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(41, 43);
                  break;
               case 27:
               case 29:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(44, 46);
                  break;
               case 32:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(47, 48);
                  break;
               case 34:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(49, 50);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 36 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjStopStringLiteralDfa_1(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1200000000L) != 0L)
         {
            jjmatchedKind = 43;
            return 38;
         }
         return -1;
      case 1:
         if ((active0 & 0x200000000L) != 0L)
            return 38;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_1(int pos, long active0)
{
   return jjMoveNfa_1(jjStopStringLiteralDfa_1(pos, active0), pos + 1);
}
private final int jjStartNfaWithStates_1(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_1(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 4);
      case 38:
         jjmatchedKind = 38;
         return jjMoveStringLiteralDfa1_1(0x80L);
      case 41:
         return jjStopAtPos(0, 37);
      case 50:
         return jjMoveStringLiteralDfa1_1(0x1000000000L);
      case 59:
         jjmatchedKind = 39;
         return jjMoveStringLiteralDfa1_1(0x200L);
      case 60:
         jjmatchedKind = 34;
         return jjMoveStringLiteralDfa1_1(0x4000000d400L);
      case 62:
         jjmatchedKind = 35;
         return jjMoveStringLiteralDfa1_1(0x12800L);
      case 105:
         return jjMoveStringLiteralDfa1_1(0x200000000L);
      case 124:
         jjmatchedKind = 40;
         return jjMoveStringLiteralDfa1_1(0x100L);
      default :
         return jjMoveNfa_1(0, 0);
   }
}
private final int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         else if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(1, 12);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(1, 13);
         break;
      case 59:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(1, 9);
         break;
      case 60:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_1(active0, 0x8000L);
      case 62:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(1, 11);
         else if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(1, 14);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(1, 36);
         break;
      case 91:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 42);
         break;
      case 110:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_1(1, 33, 38);
         break;
      case 124:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(1, 8);
         else if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(1, 16);
         break;
      default :
         break;
   }
   return jjStartNfa_1(0, active0);
}
private final int jjMoveStringLiteralDfa2_1(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_1(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(2, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_1(1, active0);
}
private final int jjMoveNfa_1(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 38;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 38:
                  if ((0xa7fffc2affffd9ffL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAddStates(51, 54);
                  }
                  else if (curChar == 36)
                     jjCheckNAdd(15);
                  if ((0x87ffc40000000000L & l) != 0L)
                     jjCheckNAddStates(55, 58);
                  else if (curChar == 61)
                  {
                     if (kind > 49)
                        kind = 49;
                  }
                  else if (curChar == 36)
                     jjCheckNAdd(14);
                  if (curChar == 36)
                     jjCheckNAdd(7);
                  if (curChar == 36)
                     jjCheckNAdd(6);
                  break;
               case 0:
                  if ((0xa7fffc2affffd9ffL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAddStates(51, 54);
                  }
                  else if (curChar == 39)
                     jjCheckNAddStates(59, 62);
                  else if (curChar == 34)
                     jjCheckNAddStates(63, 68);
                  else if (curChar == 36)
                     jjCheckNAddStates(69, 72);
                  if ((0x87ffc40000000000L & l) != 0L)
                     jjCheckNAddStates(55, 58);
                  else if (curChar == 36)
                     jjCheckNAddTwoStates(6, 14);
                  else if (curChar == 35)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(1);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 44)
                        kind = 44;
                  }
                  break;
               case 1:
                  if ((0xfffffffffffffbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if ((0xa7fffc2affffd9ffL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(51, 54);
                  break;
               case 4:
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(51, 54);
                  break;
               case 5:
                  if (curChar == 36)
                     jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0x83ff040800000000L & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(73, 77);
                  break;
               case 8:
                  jjAddStates(78, 79);
                  break;
               case 10:
                  if (curChar == 36)
                     jjCheckNAdd(7);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) != 0L && kind > 44)
                     kind = 44;
                  break;
               case 12:
                  if ((0x87ffc40000000000L & l) != 0L)
                     jjCheckNAddStates(55, 58);
                  break;
               case 13:
                  if (curChar == 36)
                     jjCheckNAdd(14);
                  break;
               case 14:
                  if ((0x83ff040800000000L & l) != 0L)
                     jjCheckNAddStates(80, 84);
                  break;
               case 16:
                  jjAddStates(85, 86);
                  break;
               case 18:
                  if (curChar == 36)
                     jjCheckNAdd(15);
                  break;
               case 19:
                  if (curChar == 61 && kind > 49)
                     kind = 49;
                  break;
               case 20:
                  if (curChar == 36)
                     jjCheckNAddTwoStates(6, 14);
                  break;
               case 21:
                  if (curChar == 36)
                     jjCheckNAddStates(69, 72);
                  break;
               case 22:
                  if (curChar == 40 && kind > 48)
                     kind = 48;
                  break;
               case 23:
                  if (curChar == 60)
                     jjCheckNAdd(22);
                  break;
               case 24:
                  if (curChar == 34)
                     jjCheckNAddStates(63, 68);
                  break;
               case 25:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(87, 89);
                  break;
               case 27:
                  jjCheckNAddStates(87, 89);
                  break;
               case 28:
                  if (curChar == 34 && kind > 43)
                     kind = 43;
                  break;
               case 29:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(90, 92);
                  break;
               case 31:
                  jjCheckNAddStates(90, 92);
                  break;
               case 32:
                  if (curChar == 34)
                     jjCheckNAdd(19);
                  break;
               case 33:
                  if (curChar == 39)
                     jjCheckNAddStates(59, 62);
                  break;
               case 34:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(34, 35);
                  break;
               case 35:
                  if (curChar == 39 && kind > 43)
                     kind = 43;
                  break;
               case 36:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(36, 37);
                  break;
               case 37:
                  if (curChar == 39)
                     jjCheckNAdd(19);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 38:
                  if ((0xefffffffffffffffL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAddStates(51, 54);
                  }
                  if ((0x2ffffffeaffffffeL & l) != 0L)
                     jjCheckNAddStates(55, 58);
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 0:
                  if ((0xefffffffffffffffL & l) != 0L)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAddStates(51, 54);
                  }
                  if ((0x2ffffffeaffffffeL & l) != 0L)
                     jjCheckNAddStates(55, 58);
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 1:
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 2:
                  if ((0xefffffffffffffffL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(51, 54);
                  break;
               case 3:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 4:
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(51, 54);
                  break;
               case 6:
                  if ((0x7fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(73, 77);
                  break;
               case 7:
                  if (curChar == 123)
                     jjCheckNAdd(8);
                  break;
               case 8:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 9:
                  if (curChar != 125)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(51, 54);
                  break;
               case 12:
                  if ((0x2ffffffeaffffffeL & l) != 0L)
                     jjCheckNAddStates(55, 58);
                  break;
               case 14:
                  if ((0x7fffffe87ffffffL & l) != 0L)
                     jjCheckNAddStates(80, 84);
                  break;
               case 15:
                  if (curChar == 123)
                     jjCheckNAdd(16);
                  break;
               case 16:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(16, 17);
                  break;
               case 17:
                  if (curChar == 125)
                     jjCheckNAddStates(55, 58);
                  break;
               case 25:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(87, 89);
                  break;
               case 26:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  jjCheckNAddStates(87, 89);
                  break;
               case 29:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(90, 92);
                  break;
               case 30:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  jjCheckNAddStates(90, 92);
                  break;
               case 34:
                  jjAddStates(49, 50);
                  break;
               case 36:
                  jjAddStates(93, 94);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 38:
               case 2:
               case 4:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(51, 54);
                  break;
               case 0:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddStates(51, 54);
                  break;
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 8:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(78, 79);
                  break;
               case 16:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(85, 86);
                  break;
               case 25:
               case 27:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(87, 89);
                  break;
               case 29:
               case 31:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(90, 92);
                  break;
               case 34:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(49, 50);
                  break;
               case 36:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(93, 94);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 38 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   10, 11, 16, 17, 3, 4, 9, 3, 4, 9, 10, 11, 16, 17, 32, 33, 
   34, 35, 23, 24, 26, 27, 28, 30, 6, 20, 21, 13, 3, 4, 5, 9, 
   7, 8, 10, 11, 12, 16, 17, 14, 15, 23, 24, 26, 27, 28, 30, 32, 
   33, 34, 35, 2, 3, 5, 10, 12, 13, 18, 19, 34, 35, 36, 37, 25, 
   26, 28, 29, 30, 32, 7, 22, 23, 15, 2, 3, 5, 6, 10, 8, 9, 
   12, 13, 14, 18, 19, 16, 17, 25, 26, 28, 29, 30, 32, 36, 37, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, "\12", null, "\73", "\46\46", "\174\174", "\73\73", 
"\74\74", "\76\76", "\74\46", "\76\46", "\74\76", "\74\74\55", "\76\174", "\151\146", 
"\145\154\151\146", "\164\150\145\156", "\145\154\163\145", "\146\151", "\144\157", 
"\144\157\156\145", "\143\141\163\145", "\145\163\141\143", "\167\150\151\154\145", 
"\165\156\164\151\154", "\146\157\162", "\173", "\41", "\50", "\175", "\151\156", "\74", "\76", 
"\62\76", "\51", "\46", "\73", "\174", null, "\74\133", null, null, null, null, null, 
null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
   "CMD", 
};
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, 0, 0, -1, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, 0, 0, 0, 1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x31fffffffffd1L, 
};
static final long[] jjtoSkip = {
   0x2eL, 
};
static final long[] jjtoSpecial = {
   0x20L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[38];
private final int[] jjstateSet = new int[76];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public ShellParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public ShellParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 38; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       try { input_stream.backup(0);
          while (curChar <= 32 && (0x100002200L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       try { input_stream.backup(0);
          while (curChar <= 32 && (0x100002200L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else 
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 28 :
        if (image == null)
            image = new StringBuffer();
            image.append(jjstrLiteralImages[28]);
                         in_for = true ;
         break;
      case 33 :
        if (image == null)
            image = new StringBuffer();
            image.append(jjstrLiteralImages[33]);
                    if( ! in_for ) matchedToken.kind = WORD ; in_for = false ;
         break;
      case 42 :
        if (image == null)
            image = new StringBuffer();
            image.append(jjstrLiteralImages[42]);
                matchedToken.image = readXExpr();
         break;
      case 48 :
        if (image == null)
            image = new StringBuffer();
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                matchedToken.image += readParen();
         break;
      default : 
         break;
   }
}
}
